"""
PlanningRun model — AI-1 E6.

One row per run_planning() invocation. Written at run start, checkpoints
appended after each agent, finalised (COMPLETED / FAILED) at run end.

Uses a separate DB connection in the checkpoint writers so checkpoint commits
are independent of the main planning transaction — a Phase 2 rollback does
not destroy already-written Phase 1 checkpoints.

Status flow:
  IN_PROGRESS → COMPLETED
  IN_PROGRESS → FAILED (unrecoverable)
  IN_PROGRESS → BLOCKED_WAITING_USER (transient classified as blocker)
  IN_PROGRESS → RETRYING (Celery retry in progress)
"""
import uuid

from sqlalchemy import Column, Date, DateTime, ForeignKey, Integer, String
from sqlalchemy.dialects.postgresql import JSONB, UUID

from app.models.base import Base, TimestampMixin, TenantMixin


class PlanningRun(Base, TimestampMixin, TenantMixin):
    __tablename__ = "planning_runs"

    # run_id generated by runner.py before pipeline starts — also used in WS channel
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Optional link to a planning session (set when called from session service)
    session_id = Column(
        UUID(as_uuid=True),
        ForeignKey("planning_sessions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    plan_date = Column(Date, nullable=False, index=True)

    # IN_PROGRESS | COMPLETED | FAILED | BLOCKED_WAITING_USER | RETRYING
    status = Column(String(30), nullable=False, default="IN_PROGRESS", index=True)

    # Last phase / agent written — used for resume and WS progress display
    current_phase = Column(Integer, nullable=True)
    current_agent = Column(String(100), nullable=True)

    # [{agent_name, phase, status, elapsed_ms, output_preview, warnings[], completed_at}]
    checkpoints = Column(JSONB, nullable=True, default=list)

    # Set on FAILED / BLOCKED_WAITING_USER: {agent_name, phase, error_type, message, is_transient}
    error_info = Column(JSONB, nullable=True)

    # Original call params stored for resume: {tenant_id, plan_date, session_id, session_hints}
    params = Column(JSONB, nullable=True)

    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)
